--- #YAML:1.0
name:               Crypt-SSLeay
version:            0.59_01
abstract:           OpenSSL support for LWP
author:
    - A. Sinan Unur <nanis@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0.88
    Try::Tiny:   0.09
requires:
    LWP::Protocol::https:  6.02
    MIME::Base64:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
